name       : python-termcolor
version    : 1.1.0
release    : 4
source     :
    - https://pypi.python.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz : 1d6d69ce66211143803fbc56652b41d73b4a400a2891d7bf7a1cdf4c02de613b
license    : MIT
component  : programming.python
summary    : ANSII Color formatting for output in terminal.
description: |
    ANSII Color formatting for output in terminal.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
